FROM mariadb:latest

EXPOSE 3306

LABEL version="1.0"
LABEL description="MariaDB Server"

ENV DATABASE_MODE=IGNORE

# ADD iSpindel_DB.sql /docker-entrypoint-initdb.d
# RUN echo "GRANT ALL PRIVILEGES ON *.* TO iSpindel;" > my_grants.sql

